/*

### Purpose

The `adn_common_fixed_priority_arbiter` arbitrates among `NUM_REQ` requesters using fixed low-index
priority. When `allow_req_i` is asserted, the lowest asserted bit in `req_i` is reported through `gnt_addr_o` and marked valid by
`gnt_addr_valid_o`.

### Usage

Set `NUM_REQ` to the number of requesters. Assert `allow_req_i` and drive `req_i`;
`gnt_addr_o` identifies the selected requester when `gnt_addr_valid_o` is high.

| REVISION | DATE       | AUTHOR             | DESCRIPTION     |
|----------|------------|--------------------|-----------------|
| 0.1      | 2026-07-30 | Shykul Islam Siam  | Initial version |
| 1.0      | 2026-07-30 | Shykul Islam Siam  | Stable release  |

Author : Shykul Islam Siam (shykulislam32@gmail.com)
This file is part of ADN-VLSI/adn_common
Copyright (c) 2026 ADN Semiconductors
Licensed under the MIT License
See LICENSE file in the project root for full license information

*/

module adn_common_fixed_priority_arbiter #(
    // PARAMETERS
    parameter int NUM_REQ = 4  // Number of request inputs; must be at least two.
    // LOCALPARAMS
) (
    // PORTS
    input  logic                       allow_req_i,       // Enables valid grant reporting.
    input  logic [    NUM_REQ-1:0]     req_i,             // Request vector.
    output logic [$clog2(NUM_REQ)-1:0] gnt_addr_o,        // Address of the selected requester.
    output logic                       gnt_addr_valid_o   // Indicates a valid selected requester.
);

//////////////////////////////////////////////////////////////////////////////////////////////////
// SIGNALS
//////////////////////////////////////////////////////////////////////////////////////////////////

logic addr_valid_o;  // Valid indication generated by the priority encoder.

//////////////////////////////////////////////////////////////////////////////////////////////////
// ASSIGNMENTS
//////////////////////////////////////////////////////////////////////////////////////////////////

// A grant is visible only when request arbitration is enabled.
assign gnt_addr_valid_o = allow_req_i & addr_valid_o;

//////////////////////////////////////////////////////////////////////////////////////////////////
// SUBMODULES
//////////////////////////////////////////////////////////////////////////////////////////////////

// Selects the lowest-index asserted request.
adn_common_priority_encoder #(
    .NUM_WIRE(NUM_REQ),
    .HIGH_INDEX_PRIORITY(0)
) priority_encoder_dut (
    .d_i(req_i),
    .addr_o(gnt_addr_o),
    .addr_valid_o(addr_valid_o)
);

//////////////////////////////////////////////////////////////////////////////////////////////////
// INITIAL CHECKS
//////////////////////////////////////////////////////////////////////////////////////////////////

`ifdef SIMULATION
initial begin
if (NUM_REQ < 2) begin
$display("\033[1;33m%m NUM_REQ must be at least 2; got %0d\033[0m", NUM_REQ);
end
end
`endif  // SIMULATION

endmodule